// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fxedsqmivzrqoqdpragj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZWRzcW1pdnpycW9xZHByYWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjMyNTcsImV4cCI6MjA3Njc5OTI1N30.5yIEmtAoQWXhpJWHAVGugPVJe3puC9W9uMQHUGXaap8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);